spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/banking_core_service
    username: root
    password: example
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true


server:
  port: 8092

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka

info:
  app:
    name: ${spring.application.name}
